// Setores predefinidos com base na tabela de preços oficial da Pro Delphus.
// É apenas uma lista de sugestões — o campo em si é texto livre.
export const PREDEFINED_SECTORS = [
  'Laparoscopy',
  'Laparoscopy with Insufflation',
  'Laparoscopy and Robotics',
  'Hysteroscopy',
  'Uterus - for use with scissors and grasper / diagnosis only',
  'Uterus - for resection',
  'Prepartum',
  'Postpartum',
  'Egg Collection and Embryo Transfer',
  'Pelvic Floor Dystopia',
  'Pelvic Bidigital Touch Examination',
  'Endourology - Prostate Touch',
  'Proctology',
  'Suture Models',
  'Suture Disc',
  'Neo-Knot',
  'Suture Models w/ Velcro for Neo Knot',
  'Wound Trainers',
  'Buco-Maxillo-Facial',
  'TMJ',
  'Sialendoscopy',
  'Knee',
  'Spine',
  'Shoulder',
  'Pediatric Traumatology and Orthopedics - Leg',
  'Thoracic Trauma',
  'Pectus Excavatum',
  'Thor A2 2nd Generation',
  'Hip Surgeries',
  'Breast Surgery',
  'Rhinoplasty',
  'VLV Ninfotrainer',
  'Hypospadia',
  'Migraine Injection',
  'Facial Landmarks for Botox Application',
  'Facial Harmonization',
  'Venous Puncture',
  'Pediatric Intraosseous Puncture',
  'Vascular Injection',
  'Herniorraphy',
  'Birth',
  'Lab - Heart',
  'Lab - Kidney',
  'Lab - Stomach/Esophagus',
  'Lab - Liver',
  'Lab - Viscera and Intestines',
  'Lab - Lung',
  'Lab - Obstructed Blood Vessels',
  'Lab - Max Trauma',
  'Lab - Half Uterus',
  'Lab - Male Genitals',
  'Lab - Breasts',
  'Lab - Hemorrhoids',
] as const
